Recent theories in the field of cognitive enhancement suggest that people's belief about whether or not cognitive abilities can be improved influences the outcome of a training program. In this week's assignment, we take a look at a dataset including two different kinds of feedback given to participants in a cognitive training program, either fixed (cognitive abilities are innate and cannot be improved) or malleable (cognitive abilities are largely driven by experiences). DVs include verbal, spatial, and intelligence measures,provided before and after training.
### Question 1
Using a t-test, compare verbal scores before and after training in the fixed condition. Is the difference pre-test to post-test significant?
- Yes
- No
### Question 2
What are the degrees of freedom for the comparison between pre-test and post-test for the spatial scores?
- 49
- 50
- 94
- 95
### Question 3
Run a Wilcoxon test for the same comparison (pre-test to post-test on spatial scores, fixed condition). Which of the two tests gives the highest p-value for the comparison?
- t-test
- Wilcoxon
### Question 4
What is the effect size (Cohen's d) for the difference between pre-test and post-test spatial scores for the malleable condition? (round to two decimal places)


### Question 5
Which of the three tasks shows the largest improvements from pre-test to post-test, in the fixed condition?
- Verbal
- Spatial
- Intel
### Question 6
Which of the three tasks shows the largest improvements from pre-test to post-test, in the malleable condition?
- Verbal
- Spatial
- Intel

### Question 7
Conduct **Mann-Whitney** comparisons between all tasks at pre-test. Which task(s) differ significantly from the other two in pre-test scores?
Verbal
Spatial
Intel
All

### Question 8
Which feedback condition led to the largest improvements overall?
- fixed
- malleable

### Question 9
Which task is largely driving this effect?
- Verbal
- Spatial
- Intel
- None in particular

### Question 10
Based on the present data, are you convinced that malleable feedback is beneficial to performance when engaging in a cognitive training program?
- Yes
- No
- It depends on the ability being trained
